Layout navbar footer
logansel/Akijaypraytay pull request #17
Opened 2021-06-02 07:47 UTC by logansel

Create component :

Layout
NavBar
Footer

2021-06-02 07:55 UTC, michelmyseth requested changes
could you change your footer position ? loglog

2021-06-02 08:11 UTC, michelmyseth submitted a review, later dismissed

2021-06-02 13:38 UTC, michelmyseth commented
Probleme par rapport a le footer il n'est pas reponsive nous avons essaye de la placer dans un container-fluid pour qu'il prenne toute la largeur de la page mais en vain

voir commit :  https://github.com/logansel/Akijaypraytay/pull/17/commits/d1408785702539326038fc9f3b995cd004dde6bf

2021-06-03 07:57 UTC, DavidAmegavi approved these changes

2021-06-03 07:57 UTC, merged